# Generated by Django 5.0.1 on 2024-05-02 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_area_no', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_limit', models.CharField(max_length=200)),
                ('parking_charge', models.CharField(max_length=200)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
                ('doc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('parking_charge', models.CharField(max_length=200)),
                ('status', models.BooleanField(choices=[(True, 'Parked'), (False, 'Leaved')], default=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('parking_area_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
